### ISSUE TITLE
Is this plugin a formal one?

### ISSUE THREAD

**Issue by Jackyuan999** [PushkinStudio/PsPushNotificationsExtended#4]
Hi, I want to know whether this plugin works well on the platform of iOS and Android? thanks a lot.

**Comment by ufna** [comment]
Currently we're not using this plugin in our games, so it's really abandoned and not up-to-day. Maybe we'll return to it a bit later (february maybe), but it's just a possibility.

So, it's recommened as an example how to integrate extended notifications to old enought UE4 version, but not as a production-ready product :)
